apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-agent
  namespace: gitlab-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-agent
  namespace: gitlab-agent
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-agent
  namespace: gitlab-agent
subjects:
  - kind: ServiceAccount
    name: gitlab-agent
    namespace: gitlab-agent
roleRef:
  kind: Role
  name: gitlab-agent
  apiGroup: rbac.authorization.k8s.io
