apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  labels:
    okbtsp.corp/department: OIT
    okbtsp.corp/owner: baranav
    okbtsp.corp/project: gitlab-agent
  name: gitlab-agent
  namespace: fleet-default
spec:
  branch: master
  caBundle: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZtakNDQklLZ0F3SUJBZ0lUWVFBQUFBVU93M25heFFzV2hRQUFBQUFBQlRBTkJna3Foa2lHOXcwQkFRc0YKQURBNk1UZ3dOZ1lEVlFRREV5OUpibVp5WVM1amIzSndJRU5zWVhOeklERWdVbTl2ZENCRFpYSjBhV1pwWTJGMAphVzl1SUVGMWRHaHZjbWwwZVRBZUZ3MHlOVEF6TXpFeE5ETXlNRGhhRncwek1EQXpNekV4TkRReU1EaGFNSUdNCk1Rc3dDUVlEVlFRR0V3SkNXVEVUTUJFR0ExVUVDQk1LUW1Wc1lYSjFjMmxoYmpFT01Bd0dBMVVFQnhNRlRXbHUKYzJzeERqQU1CZ05WQkFvVEJVbE9SbEpCTVF3d0NnWURWUVFMRXdOUFNWUXhHekFaQmdOVkJBTVRFa3M0YzBOQgpMbTlyWW5SemNDNXNiMk5oYkRFZE1Cc0dDU3FHU0liM0RRRUpBUllPYjJsMFFHOXJZblJ6Y0M1amIyMHdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHFVS0FTVzlraGFxdDJDZmRLenIxRVo0TWYKY25TS1VtcFU1N05oL3ZhTVlnOW0wcmovazJPUFJMOTZHenFyY05FcS9DcXdLbWxONUhYVkJ3UFU4RDd4cTJNdgoraXN3akZuM2ZCOXJUNGhEZjBYbUNhRkdENFdpV0xWMU1MQy9CdmVkZUwzbE9Ob1dlOWJQRUp1ajBSSy9MbldBCjRuVWwyNEIwYVVmaTk2VllYUUgrbHUvaWM2MVRialpKNFJsaEV2Vm9PQmdmcmZ3SjIrMWNub0ZmcTlDNWROODEKOExtUXZBak43TUZLZWZQT0V3YUYzYXFEYmNCVStyUDdXSGx2LzhoUXM3bDE4L3NDVTZJU0o2ZEFkMWl0YUJ5Swpoc1U2S3AzZU0vOUdiRnNaQTduSFh4ZStZVmxIbnNjY2ZsSW1NbWVkUERlT0pzYmMvTEVFMzVQZ2xST1ZBZ01CCkFBR2pnZ0pFTUlJQ1FEQWRCZ05WSFE0RUZnUVV2Vlg4SURBSFJ6QlhWU1A1ZWxCSTFGcjhVd1V3SHdZRFZSMGoKQkJnd0ZvQVVuOXZPMlowMHdoQjd0akZVUUZEQUtIa0p5azB3Z2RJR0ExVWRId1NCeWpDQnh6Q0J4S0NCd2FDQgp2b1plYUhSMGNEb3ZMM0JyYVM1dmEySjBjM0F1Ykc5allXd3ZRMlZ5ZEVSaGRHRXZTVzVtY21FdVkyOXljQ1V5Ck1FTnNZWE56SlRJd01TVXlNRkp2YjNRbE1qQkRaWEowYVdacFkyRjBhVzl1SlRJd1FYVjBhRzl5YVhSNUxtTnkKYklaY2FIUjBjRG92TDNCcmFTNXBibVp5WVM1amIzSndMME5sY25SRVlYUmhMMGx1Wm5KaExtTnZjbkFsTWpCRApiR0Z6Y3lVeU1ERWxNakJTYjI5MEpUSXdRMlZ5ZEdsbWFXTmhkR2x2YmlVeU1FRjFkR2h2Y21sMGVTNWpjbXd3CmdlOEdDQ3NHQVFVRkJ3RUJCSUhpTUlIZk1IUUdDQ3NHQVFVRkJ6QUNobWhvZEhSd09pOHZjR3RwTG05clluUnoKY0M1c2IyTmhiQzlEWlhKMFJHRjBZUzlTYjI5MFEwRXRNREZmU1c1bWNtRXVZMjl5Y0NVeU1FTnNZWE56SlRJdwpNU1V5TUZKdmIzUWxNakJEWlhKMGFXWnBZMkYwYVc5dUpUSXdRWFYwYUc5eWFYUjVMbU55ZERCbkJnZ3JCZ0VGCkJRY3dBb1piYUhSMGNEb3ZjR3RwTG1sdVpuSmhMbU52Y25BdlEyVnlkRVJoZEdFdlVtOXZkRU5CTFRBeFgwbHUKWm5KaExtTnZjbkFnUTJ4aGMzTWdNU0JTYjI5MElFTmxjblJwWm1sallYUnBiMjRnUVhWMGFHOXlhWFI1TG1OeQpkREFaQmdrckJnRUVBWUkzRkFJRURCNEtBRk1BZFFCaUFFTUFRVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQXNHCkExVWREd1FFQXdJQmhqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFaTE1hSERtMm5qVzNJK2VXWDhnbGlydHIKQndkTmF5NHJ5cmFNQTdXcHpudVdRYnBUemVmVmdDUEwzaGNGNG5aZkdKM3MvZHlUZk5mZVlrb0E4M2F0enV6RwpheFRhbnhlNDA1QXZuSjVrOFpuQXVOTms1TGNuQWpDUk1rdFBwbTIzck9OMEF0ZUdzcDB6L3NiNW10L0IvVzhPClNFd1RxTWVxdE5HSzRFUndxV1lhaVg4blZOTDVWZmhDeEtqbDhpMGl6TTV3RzlWZnBHRXY4dEp3NDNvNmR4eWMKVWtaTmo4MkpPdFdmc1h0dXB4T0IyNE9mMVpaNEZyQWVEMForeXkwZ2x6dkVJSmtrckJ2MlVLZEMvRjFxZzhCTgpZQ2tCaWl6bVdOUWlmckxPcGg2R0RJUjBxSVl3ZFNTZkZuenJWckN5ZjkzRmtGM0h6M1JQSm1kdXFRTjNIdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  clientSecretName: auth-57vqc
  correctDrift:
    enabled: true
    force: true
  forceSyncGeneration: 2
  paths:
    - gitlab-token
    - gitlab-agent
  pollingInterval: 1m0s
  repo: ssh://git@gitlab.okbtsp.corp:2222/oit/k8s/k8s-gitlab-agent-01.git
  targets:
    - name: management
      clusterSelector:
        matchLabels:
          okbtsp.corp/department: OIT
          okbtsp.corp/owner: baranav
          okbtsp.corp/template: rancher-k3s

    - name: prod
      clusterSelector:
        matchLabels:
          okbtsp.corp/department: OIT
          okbtsp.corp/owner: baranav
          okbtsp.corp/template: talos-vmware
